### ISSUE TITLE
Is Minecraft a voxels game? What are voxels?

### ISSUE THREAD

**Issue by acs** [Voxelers/mcthings#91]
Understanding voxels is an interesting topic. As a summary a voxel (volume element) is a pixel (picture element) in 3D. My current thought: Minecraft uses voxels for representing the world, and it uses cubes for presenting it (a cube is a polygon, not a voxel, so it can be drawn quickly).

But all of these is new for me, so probably I would change my mind during the learning trip.

The first article after reading others that attract my attention:

https://medium.com/retronator-magazine/pixels-and-voxels-the-long-answer-5889ecc18190

I have also read https://en.wikipedia.org/wiki/Voxel

**Comment by acs** [comment]
[![Vector vs Raster](https://miro.medium.com/max/1150/1*UCXcMq6rXDhmG1eI9dcYuQ.png)](https://medium.com/retronator-magazine/pixels-and-voxels-the-long-answer-5889ecc18190)

**Comment by acs** [comment]
A nice tool to play with:

https://medium.com/tech-notes-and-geek-stuff/install-magicavoxel-win-64-on-linux-d90236fdf927

**Comment by acs** [comment]
«Voxel engines couldn’t keep up with the performance of polygon graphics and so voxels died …

… until about ten years later when one game took them to a whole new level of popularity. The game left the old ways behind and paved the way for the voxel-as-a-cube approach. By now this could be efficiently rendered using GPUs and the rest is history.»

So voxels are rendered as cubes, and it could use the GPUs. Cubes are rendered as triangles, which are the GPUs way to draw things.

«The most prominent example of this is of course Minecraft. Although Minecraft blocks are voxels by definition (they are the smallest discrete volume units in the game), they come in a wide variety of types represented by low-poly models with pixel art textures. Even though they are blocky, many of them are not simple cubes.» The 2D textures are drawn in the cubes (voxels) and they can change how the cube looks like (and sometimes it is not a cube anymore).

**Comment by acs** [comment]
[![Voxels Minecraft](https://miro.medium.com/max/1150/1*b6twwj1cNKuUL8sbcBtBGg.png)](https://medium.com/retronator-magazine/pixels-and-voxels-the-long-answer-5889ecc18190)

**Comment by acs** [comment]
Ok, now I have more info about what are voxels and many other things (textures for example). Time to close this ticket!

**Comment by javiercuervo** [comment]
Minecraft is a good example of a popular voxel based game, which leverages the gameplay potential of voxel terrain and interactions. It “cheats” in the sense that the voxels are just polygonal cubes, but the math involved in procedurally generating terrain in Minecraft will be familiar to anybody who has ever tinkered with a voxel based terrain engine from any other game.
https://medium.com/predict/why-voxels-are-the-future-of-video-games-vr-and-simulating-reality-98d71b84c377

**Comment by acs** [comment]
I will play a bit more with voxels to understand all better with real examples. I would play with Blender and https://medium.com/tech-notes-and-geek-stuff/install-magicavoxel-win-64-on-linux-d90236fdf927

**Comment by acs** [comment]
Yes, Minecraft is a Voxels game that uses low-pol and low-res textures so scalability and performance are great, and it is easier to create contents for it because all the graphics stuff is basic and limitated. 

It goes in the same line of games like https://openspades.yvt.jp/.
