### ISSUE TITLE
Design and Implement vox2schematic tool

### ISSUE THREAD

**Issue by acs** [Voxelers/mcthings#99]
This tool must be used to import voxels and meshes into McThings (schematics format).

https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt
https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt

The primary goal is to import from vox format fo schematic. For that:

* Analyze: https://github.com/abrightmoore/voxtoschematicparser/blob/master/Vox2Schematic_v3.py
* Research and improve: https://github.com/alexhunsley/numpy-vox-io (https://github.com/juntosdesdecasa/mcthings/issues/95#issuecomment-643649172) so we have a Python lib for reading vox format (there are sample in python https://github.com/juntosdesdecasa/mcthings/issues/95#issuecomment-643649172)
* Define howto map colors to minecraft blocks: have in mind that it must support legacy mapping and the new sponge format.
* This importer will support other input formats: have it in mind during the design
* Probably the name vox2schematic will be the right one for the tool based on this library

**Comment by acs** [comment]
Related to this one: https://github.com/juntosdesdecasa/mcthings/issues/100

**Comment by acs** [comment]
Maybe we should extend:

https://gitlab.com/bztsrc/mtsedit/blob/master/docs/batch.md

so it exports Schematic format. And that's all!

Add a 

`  -S: output to Schematic`

It is implemented in **C language**, like GNOME :)

**Comment by acs** [comment]
vox has several importers at:

https://github.com/Zarbuz/FileToVox

So the writting of vox files is well covered here.

And probably also the reading if they have good tests. It is implemented in C# and here we have the reader and writer:

https://github.com/Zarbuz/FileToVox/tree/master/SchematicToVoxCore/Vox

In this tool, it seems all the formats are comnverted to Schematics and the Schematics is converted to Vox. In McThings, my guess is that we will use also Schematics format as the common one. Why? Becase it has solid tools to process it (NBTtools) and the format is simple and flexible and complete.

**Comment by acs** [comment]
The writing to vox format seems to be pretty easy:

https://gitlab.com/bztsrc/mtsedit/-/commit/80569a64c0c91080699f46fd9a1302b14b1847b2

and it uses the Y, X, Z order as in schematics. 

it is writing a header, the data and the palette. If it is so easy to do, probably we can just implement it from scratch and later, create a library with support for reading and writing VOX files like the NBT library.

**Comment by acs** [comment]
The process for a guy doing the same for Three.js: https://luciopaiva.com/magicavoxel-threejs-howto/

**Comment by acs** [comment]
VOX uses RIFF format, and in Python there is a module built-in for reading this kind of data:

https://docs.python.org/3.8/library/chunk.html

Great!

So we can do a clean job reading and writing VOX files.

**Comment by acs** [comment]
So my conclusion is that VOX format is so easy to read and write that:

* Implement reader and writer for Python using the RIFF Python module. Support both vox formats if possible.
* The schematic writer is already implemented in McThings, so we just need to read the VOX file, map the voxels color and material to a Minecraft block (using mcpi.block) and save all in schematic format.
*The parsing will be implemented with objects representing the [core concepts](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt): 
  * Models
  * Material
  * Palette
  * Scene
  * World

So we have a plan!

**Comment by acs** [comment]
The name of the first library was vox-io. Not bad. I will use **voxpy** probably. 

![Screenshot from 2020-06-15 00-40-38](https://user-images.githubusercontent.com/209533/84605841-e2b90c80-aea0-11ea-85d0-4ddc6c9f66f1.png)

**Comment by acs** [comment]
https://github.com/RichysHub/MagicaVoxel-VOX-importer Blender importer for VOX format implemented in Python. A good reference.

And also in https://github.com/jpaver/opengametools they have a reader and writter implemented in C++ based on a vox parser C++ library.

For JS: https://github.com/dgoemans/VoxRenderer

**Comment by acs** [comment]
Some experiences supporting the new format:

https://github.com/RichysHub/MagicaVoxel-VOX-importer/issues/6

**Comment by acs** [comment]
A very useful command to see the structure of the vox file:

```
(venv) strings vxs.vox 
VOX 
MAIN
SIZE
XYZI
nTRN
nGRP
nTRN-
-1 -1 2nSHP
LAYR
_name
LAYR
_name
LAYR
_name
LAYR
_name
LAYR
_name
LAYR
_name
LAYR
_name
LAYR
_name
RGBA
MATL
_type
_diffuse
_weight
_rough
_spec
_spec_p
_ior
_att
-0.5
_flux
_ldr
0MATL
....

```

**Comment by acs** [comment]
The proposed reading process for chunks in python lib:

`«Usually an IFF-type file consists of one or more chunks. The proposed usage of the Chunk class defined here is to instantiate an instance at the start of each chunk and read from the instance until it reaches the end, after which a new instance can be instantiated. At the end of the file, creating a new instance will fail with an EOFError exception.»`

Let's try to follow it! Start a new chunk given the position of the chunk on the file.

A nice example doing just that here: https://www.programcreek.com/python/example/93077/chunk.Chunk

The key is to create Chunk with the file positioned correctly for reading the next chunk. Part of:

https://github.com/pyblish/pyblish-win/blob/master/lib/Python27/Lib/wave.py

And indeed this is a pretty interesing project: https://pyblish.com/ «Pyblish is what enables our artists to focus more on the artistic barrier of raising quality instead of the technical one whilst maintaining a pipeline that raises the bar for both.»

**Comment by acs** [comment]
Ok, let's try to describe at high level the format in the current version of the file (vox-extension) using the strings command output.

* File header: 4 (VOX) + 4 bytes (version ... size normally in RIFF format)
* First chunk [MAIN](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt#L10)
* Chunk Pack is missing in our samples
* [Model Chunk](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt#L15)
* [Transform Node Chunk : "nTRN"](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt#L63)
* [Group Node Chunk : "nGRP" ](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt#L82)
* nTRN
* [Shape Node Chunk nSHP](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox-extension.txt#L94)
* LAYR ... LAYR
* RGBA
* MATL ... MATL (there are thousand of them) and it is the reason why the minimal size of a VOX file is >60K
* rOBJ ... rOBJ (undocumented)
* rCAM ... rCAM (undocumented)
* NOTE (undocumented)

**Comment by acs** [comment]
So if we want to load 1 model and only the cubes, our focus must be the Model Chunk:

```
5. Chunk id 'SIZE' : model size
-------------------------------------------------------------------------------
# Bytes  | Type       | Value
-------------------------------------------------------------------------------
4        | int        | size x
4        | int        | size y
4        | int        | size z : gravity direction
-------------------------------------------------------------------------------


6. Chunk id 'XYZI' : model voxels
-------------------------------------------------------------------------------
# Bytes  | Type       | Value
-------------------------------------------------------------------------------
4        | int        | numVoxels (N)
4 x N    | int        | (x, y, z, colorIndex) : 1 byte for each component
-------------------------------------------------------------------------------

```
and the palette

```
7. Chunk id 'RGBA' : palette
-------------------------------------------------------------------------------
# Bytes  | Type       | Value
-------------------------------------------------------------------------------
4 x 256  | int        | (R, G, B, A) : 1 byte for each component
                      | * <NOTICE>
                      | * color [0-254] are mapped to palette index [1-255], e.g : 
                      | 
                      | for ( int i = 0; i <= 254; i++ ) {
                      |     palette[i + 1] = ReadRGBA(); 
                      | }
-------------------------------------------------------------------------------

```

**Comment by acs** [comment]
In the first iteration the goal is to support the last version of the format, but probably, it is easy to support older formats.

**Comment by acs** [comment]
Great, it seems it is going to be easy and clean to support VOX format. The code is taking shape at:

https://github.com/acs/mcthings/blob/99-vox2schematics/mcthings/vox.py

**Comment by acs** [comment]
Great, it is a bit tricky to use the chunk python lib to read the vox file, but once I know how to do it, it will be much maintainable having the Chunk concept supported in the logic. 2h aprox to have a first working version.

**Comment by acs** [comment]
Ok, now we can read the blocks and the colors from a MagicaVoxel file. Cool! Now it is time to map it to Minecraft. And this is a tough problem because we don't have all colors in Minecraft. Using wool we can replicate partially the colors.

https://www.stuffaboutcode.com/p/minecraft-api-reference.html

Data Values of blocks:
WOOL:
0: White
1: Orange
2: Magenta
3: Light Blue
4: Yellow
5: Lime
6: Pink
7: Grey
8: Light grey
9: Cyan
10: Purple
11: Blue
12: Brown
13: Green
14: Red
15: Black

So we need to map the RGBA colors to this ones. The best thing is to have a Minecraft palette in MagicaVoxel to create the models using them. In this case, let's do a hack:

ee 00 00 is 14.

**Comment by acs** [comment]
Ok, here we go:

![Screenshot from 2020-06-28 10-16-32](https://user-images.githubusercontent.com/209533/85942280-94881c80-b928-11ea-800d-69d19bd7821f.png)

from

![Screenshot from 2020-06-28 10-19-11](https://user-images.githubusercontent.com/209533/85942335-d31dd700-b928-11ea-9a14-bb5dbcfc64e8.png)

**Comment by acs** [comment]
![mv2mc](https://user-images.githubusercontent.com/209533/85942469-c0f06880-b929-11ea-9bad-4786ed715c06.png)

**Comment by acs** [comment]
Colors from 15 to 0:

![mc_colors](https://user-images.githubusercontent.com/209533/85951995-c8823280-b966-11ea-8b14-f1586d8274a2.png)

we need to create a magicavoxel palette with them (we need the hex codes for them).

```
COLORS = [
        "White",
        "Orange",
        "Magenta",
        "Light Blue",
        "Yellow",
        "Lime",
        "Pink",
        "Grey",
        "Light grey",
        "Cyan",
        "Purple",
        "Blue",
        "Brown",
        "Green",
        "Red",
        "Black"
    ]
```

https://gaming.stackexchange.com/questions/47212/what-are-the-color-values-for-dyed-wool

 • White      - FFe4e4e4 
 • Orange     - FFea7e35 
 • Magenta    - FFbe49c9 
 • Light Blue - FF6387d2 
 • Yellow     - FFc2b51c 
 • Lime Green - FF39ba2e 
 • Pink       - FFd98199 
 • Dark Gray  - FF414141 
 • Light Gray - FFa0a7a7 
 • Cyan       - FF267191 
 • Purple     - FF7e34bf 
 • Blue       - FF253193 
 • Brown      - FF56331c
 • Green      - FF364b18 
 • Red        - FF9e2b27 
• Black      - FF181414

So our next step is to create a palette in MagicaVoxel with this colors.

**Comment by acs** [comment]
But before working at the color detail, let's check all is working with some models in vox format.

One of our goals is to support the loading of:

https://github.com/mikelovesrobots/mmmm

And maybe this is the old version format. The goal is to support it also. So let's work on that.

Let's play with this one wich is 8 (z) x 4 (x) x 11 (y): 332 blocks. [alien_engi1a](https://github.com/mikelovesrobots/mmmm/blob/master/vox/alien_engi1a.vox)

![Screenshot from 2020-06-28 18-05-06](https://user-images.githubusercontent.com/209533/85952507-12204c80-b96a-11ea-8245-18244b6dad2c.png)

It has 4 colors: blue, black, gray and light gray. So an accurate job could be done!

It is a 6 years old model, and I love to support this old models!!! Let's do it :100: 

The old format is simpler:

```
(venv) strings alien_engi1a.vox 
VOX 
MAIN
SIZE
XYZI
RGBA
```

To check the correct loading of the palette we can do it in MV. For each palette there are 32 * 8 = 256 colors.

And we can check the colors in MV:

![Screenshot from 2020-06-28 21-08-22](https://user-images.githubusercontent.com/209533/85956091-9632fe00-b983-11ea-9faa-27ee37f5e7f8.png)

To check the full palette:

![Screenshot from 2020-06-28 21-01-10](https://user-images.githubusercontent.com/209533/85956072-54a25300-b983-11ea-821d-03da9b17683d.png)

In this palette the first color is (index 1): ffffff . The index 2: ffffcc.  index 3: ffff99.


and the last color is index 255 is 111111. The 249 is aaaaaa (256 can not be selected and it is not part of the palette). So the palette goes from 0 to 254 (at least in the old version). 

¿Is that the [default one](https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt)? I think so (but in the file, index 1 is 000000, and the colors are in different order: ffff99 is 99ffff.

Let's check that we are reading the palette correctly (I am pretty sure there are no issues with the blocks).

**Comment by acs** [comment]
The results are promising. 

![alien_engi1a_mc](https://user-images.githubusercontent.com/209533/85956553-bb753b80-b986-11ea-8ed0-60c200b49191.png)

As expected we need to fix the colors. But we are in the right path!

**Comment by acs** [comment]
Ok, before putting all focus in the colors transformation, let's try to conversion to Schematic. This is something already available in McThings, so just testing the plumbing.

The goal is to generate the Voxelers logo as a Schematic.

![Screenshot from 2020-06-28 23-23-45](https://user-images.githubusercontent.com/209533/85958534-735e1500-b996-11ea-856e-387a27280ca9.png)

Loaded from a Schematic. For some reason we are exporting 24 blocks instead of 6. We need to review it, but it is working in the dev branch for vox support.

![Screenshot from 2020-06-28 23-26-55](https://user-images.githubusercontent.com/209533/85958597-ecf60300-b996-11ea-8ed6-561f80bdaba7.png)

The problem is "x-axis" that must be 1 and it is 4. I will recheck it.

![Screenshot from 2020-06-29 05-29-12](https://user-images.githubusercontent.com/209533/85970073-9a820a00-b9c9-11ea-9141-aff4e1f2f3c8.png)

So the problem is the self.position. If we use init_pos and end_pos for schematic extraction, it will work. But why self.position is not init_pos? Let's review.

It is working nicely. Why? Let's take a look to MV:

![Screenshot from 2020-06-29 05-41-28](https://user-images.githubusercontent.com/209533/85970628-4aa44280-b9cb-11ea-95ee-83193fde46ef.png)

The position of z is +3, x +1 and y +0- So the blocks go from z:0, 2 x:0, 3 y:0,1 (3 x 4 x 2 = 24). So the schematic is perfect. In order to avoid the offset, we need to create in MV without offset.

![Screenshot from 2020-06-29 05-50-20](https://user-images.githubusercontent.com/209533/85971055-7b38ac00-b9cc-11ea-8bec-e875cd0baa0c.png)


And using this vox model we get in the schematic: 

`2020-06-29 05:51:12,466 Schematic: Exporting blocks: 6`

And we get the right number of blocks (3 empty blocks, and 3 red blocks)

**Comment by acs** [comment]
Ok, time to create our Minecraft wool palette for MV.

https://gaming.stackexchange.com/questions/47212/what-are-the-color-values-for-dyed-wool

```
• White -      e4e4e4
• Orange -     ea7e35
• Magenta -    be49c9
• Light Blue - 6387d2
• Yellow -     c2b51c
• Lime Green - 39ba2e
• Pink -       d98199
• Dark Gray -  414141
• Light Gray - a0a7a7
• Cyan -       267191
• Purple -     7e34bf
• Blue -       253193
• Brown -      56331c
• Green -      364b18
• Red -        9e2b27
• Black -      181414
```
![Screenshot from 2020-06-29 06-33-08](https://user-images.githubusercontent.com/209533/85973252-737c0600-b9d2-11ea-9b11-0d9df69ae83a.png)

![minecraft_wool_palette](https://user-images.githubusercontent.com/209533/85973329-b4741a80-b9d2-11ea-8e44-2f27e33ad920.png)

**Comment by acs** [comment]
![wool_wall](https://user-images.githubusercontent.com/209533/85977379-cbb80580-b9dc-11ea-894e-c3111c7a9366.png)

Mostly we have it! It is flipped but this should be easy to fix.

**Comment by acs** [comment]
Ok, just pending:

* Fix the flipped
* Review the code to refactor if if needed
* Add tests
  * Number of voxels imported/exported
  * Colors
* Define a demo plan to show the possibilities of the MV and MC integration
  * use the shaders in MV to create cool regions in MC
  * use the minibots to create a museum with them in MC
* Implement a command line tool
* Dissemination of the new feature in the forums

**Comment by acs** [comment]
In order to fix the flip issue, the best approach is to implement the flip operation in mcthings: https://github.com/Voxelers/mcthings/issues/112

But we have not a flip issue. It is just to look to the wall from the right side (the same side we use in MV).

![wool_wall_ok](https://user-images.githubusercontent.com/209533/86086565-4860e780-baa2-11ea-901e-6e4ccf74eb65.png)

But, is it the same for the alien robot? No

![alien_flip](https://user-images.githubusercontent.com/209533/86087286-236d7400-baa4-11ea-9abd-d8c44ac1101d.png)

And we have the same issue when going through vox->obj->binvox->schematic

The problem is that in general x grows in this direction >--->---> but in MC it grows in <----<-----< (and the same for z). So we need to flip.

**Comment by acs** [comment]
Much better now with the flip operation implemented.

![Screenshot from 2020-06-30 08-33-17](https://user-images.githubusercontent.com/209533/86091563-67647700-baac-11ea-8c25-00e93a785bf7.png)

**Comment by acs** [comment]
Ok, let's play with colors and then review code, improve tests, prepare demos and implement the command line tool and disseminate.

**Comment by acs** [comment]
Let's try to reproduce the alien colors in Minecraft. For doing it:

* Open the alien vox model
* Load the Minecraft palette
* Change colors to one of the 16 from Minecraft palette
* Save the vox model
* Import it in McThings and check the results

This is a general workflow to be done each time you want to have valid colors inside Minecraft.

Also, we can add more colors using other blocks in Minecraft:

* Red Stone
* Gold
* Diamond
* ...

**Comment by acs** [comment]
But first, let's check if flip_z is needed also. And let's do it by default when loading VOX data for both use cases. Let's play with the model veh_ambulance.vox:

![Screenshot from 2020-07-01 05-15-57](https://user-images.githubusercontent.com/209533/86199288-fa0f1f80-bb59-11ea-9466-674963cf71b7.png)

![Screenshot from 2020-07-01 05-23-48](https://user-images.githubusercontent.com/209533/86199733-25ded500-bb5b-11ea-8b36-1822b85dd4d0.png)

**Comment by acs** [comment]
Ok, it seems there are no flipping issues in z-axis. Let's try to recreate the ambulance colors.

For doing it, let's use the MC palette y MV.

![Screenshot from 2020-07-01 05-27-12](https://user-images.githubusercontent.com/209533/86199870-89690280-bb5b-11ea-8972-23f6c1445bee.png)

![Screenshot from 2020-07-01 05-28-12](https://user-images.githubusercontent.com/209533/86199923-af8ea280-bb5b-11ea-8c50-4cd446dcc47e.png)

To the left the original one, to the right using the MC wool colors:

![Screenshot from 2020-07-01 05-37-59](https://user-images.githubusercontent.com/209533/86200483-1791b880-bb5d-11ea-93d7-75ca41aa75f2.png)

and the result in MC:

![Screenshot from 2020-07-01 05-41-24](https://user-images.githubusercontent.com/209533/86200636-8b33c580-bb5d-11ea-8d33-098ac5147dd2.png)

The dark gray wool is getting red wool for  some reason. But the rest of the colors are ok. Bug found: the grey in this region is not the MC one, but the empty one without color!

![Screenshot from 2020-07-01 05-54-12](https://user-images.githubusercontent.com/209533/86201252-54f74580-bb5f-11ea-8b46-1fb0fd82f20d.png)

**Comment by acs** [comment]
Ok, just pending:

* Implement the command line tool
* Add unit testing using the in memory version
* Create a video doing the ambulance with colors

**Comment by acs** [comment]
Command line tool
--

vox2schematic:

* Input file to convert
* Optional output file

In the first version that's all. In new version we can add an optional map from MV colors to MC blocks/wool colors.

The tool will work from memory version of the models, so it must be pretty fast. Test it with the 400 models from Mike.

**Comment by acs** [comment]
Goals:

* Convert the ambulance and upload it to schematics
* Convert all the models in https://github.com/mikelovesrobots/mmmm/tree/master/vox and create the schematics and show them in a minecraft world.

**Comment by acs** [comment]
Ok, let's create the tool: vox2schematic. At some point it could be also interesting the schematic2vox, but I think it is less interesting.

**Comment by acs** [comment]
Ok, right now we are collecting the data in **build_schematic_nbt** from the data in the renderer. But this information is available in memory also, because we are using the Minecraft format for the memory schemas. So we need to have at least a method **build_schematic_nbt_from_memory** that uses the data in memory and that does not try to collect the data from the renderer.

But we are pretty close to have the feature implemented.

**Comment by acs** [comment]
Ok, the script is working:

`(venv) bin/vox2schematic.py ~/devel/mmmm/vox/obj_house6.vox -o tests/schematics/obj_house6.schematic`

It is slow, but increase the performace should be easy to reach a reasonable performance.

![Screenshot from 2020-07-02 18-55-42](https://user-images.githubusercontent.com/209533/86388797-ad306380-bc95-11ea-8309-0a76da78df46.png)
![Screenshot from 2020-07-02 18-55-30](https://user-images.githubusercontent.com/209533/86388799-adc8fa00-bc95-11ea-8b76-1acc54440f59.png)

For example, with this house with 78336 blocks, it has not finished yet after 5 minutes. So let's implement the first improvement.

Fixed the performance issue:

```
(venv) bin/vox2schematic.py ~/devel/mmmm/vox/obj_house6.vox -o tests/schematics/obj_house6.schematic
2020-07-02 19:12:20,855 Vox input file: /home/adelcastillo/devel/mmmm/vox/obj_house6.vox
2020-07-02 19:12:20,855 Schematic output file: tests/schematics/obj_house6.schematic
2020-07-02 19:12:22,006 Schematic: Exporting blocks: 78336
2020-07-02 19:12:22,053 Creating the memory cache with positions
2020-07-02 19:12:22,119 Done memory cache with positions
2020-07-02 19:12:22,552 Schematic export finished in 0.55 secs
```
and the schematic result is ...

![Screenshot from 2020-07-02 19-15-57](https://user-images.githubusercontent.com/209533/86390521-7e67bc80-bc98-11ea-88a6-9ee93713f69f.png)
![Screenshot from 2020-07-02 19-15-25](https://user-images.githubusercontent.com/209533/86390526-8293da00-bc98-11ea-8f10-78f30400712c.png)

**Comment by acs** [comment]
5 minutes investment colouring the house:

![Screenshot from 2020-07-02 19-21-51](https://user-images.githubusercontent.com/209533/86391579-4d888700-bc9a-11ea-844a-84c515a272e2.png)
![Screenshot from 2020-07-02 19-28-38](https://user-images.githubusercontent.com/209533/86391573-4c575a00-bc9a-11ea-81f3-610499fe0a93.png)

and the result in Minecraft:

```
(venv) bin/vox2schematic.py ~/devel/voxels/MagicaVoxel-0.99.5.1-win64/export/obj_house6-mc.vox -o tests/schematics/obj_house6-mc.schematic
....
    voxel_color = self.palette[voxel.color_index]
IndexError: list index out of range

```

Found a bug. Let's fix it! The format of the file is different, We need to improve our parser. The problem is that for some reason during colouring two models were created. Right now, only one model is supported. Fixed.

And the result house:

![Screenshot from 2020-07-03 06-25-34](https://user-images.githubusercontent.com/209533/86431814-13e56980-bcf6-11ea-8122-53d1561edb8e.png)
![Screenshot from 2020-07-03 06-24-53](https://user-images.githubusercontent.com/209533/86431817-16e05a00-bcf6-11ea-814d-1f194f5c0670.png)

**Comment by acs** [comment]
The main issue with this house is that it is for giants. So it is not at the right dimension for MC. So we need to work in MV at a smaller scale so the creations are natural inside the MC world. But this can be done. But it is a new way to create inside MV: for Minecraft. And also, the models are filled, so the house is a thick block.

So this kind of models are not useful in Minecraft to interact with them. So the question is .... is it better to create in MV that inside MC directly? My guess is that yes, but we need to improve the MC blocks can be used inside MV, and there are things that will be done better inside MC.

**Comment by acs** [comment]
Ok, so next steps:

* Add unit testing using the in memory version
* Release the tool
* Create a video doing the ambulance with colours
* Use the MV shaders to create regions and import them into MC

**Comment by acs** [comment]
Tool included in 0.51.1 and working.

Next step is to put focus in the tests!!
* Test with MV samples
* Test with https://github.com/mikelovesrobots/mmmm/tree/master/vox

**Comment by acs** [comment]
About the tool, we need to capture the exceptions if the format is not the expected one: only one model for legacy and current format.

**Comment by acs** [comment]
Hay muchos conversores de otros formatos a VOX (https://github.com/Eisenwave/voxel-io y otros proyectos), así que todos ellos los podríamos llevar a Minecraft.

**Comment by acs** [comment]
More repos with models to test the conversor: https://www.mediafire.com/folder/a0znmricqxlkz/Free_Voxels

**Comment by acs** [comment]
Should we add the multi model support? Probably not in the first iteration: it is complex to have useful results with complete scenes ... but it is pretty alignet with McThings. The scene could be broken in schematics and added individually.

**Comment by acs** [comment]
Probably if we can not convert a color to the right Minecraft one, it is better to leave the block as a grey one (or stone or a fixed block).

**Comment by acs** [comment]
Ok, next steps:

* To select the closer color to the one in MV: http://hanzratech.in/2015/01/16/color-difference-between-2-colors-using-python.html ([SO](https://stackoverflow.com/questions/9018016/how-to-compare-two-colors-for-similarity-difference))
* Add tests
* If the parsing fails (bad format file, multiscene file ...) provide a controlled output

**Comment by acs** [comment]
Using an improved version of the automatic coloring based on the above proposal the results are:

![Screenshot from 2020-07-04 09-08-18](https://user-images.githubusercontent.com/209533/86507165-3babfe80-bdd6-11ea-93d5-f9aa2c974265.png)
![Screenshot from 2020-07-04 09-11-47](https://user-images.githubusercontent.com/209533/86507193-862d7b00-bdd6-11ea-86ae-039696c0d69a.png)
![Screenshot from 2020-07-04 09-08-36](https://user-images.githubusercontent.com/209533/86507162-3949a480-bdd6-11ea-8002-c3f20765b2d0.png)
![Screenshot from 2020-07-04 09-12-00](https://user-images.githubusercontent.com/209533/86507194-8ded1f80-bdd6-11ea-83a6-b568df59fe8f.png)
![Screenshot from 2020-07-04 09-12-22](https://user-images.githubusercontent.com/209533/86507195-9180a680-bdd6-11ea-94ee-e2a8315cc93a.png)

**Comment by acs** [comment]
Ok, time to close this ticket! The tool is ready, with doc and tweeter dissemination also done. Let's see the impact.

https://github.com/Voxelers/mcthings/tree/develop/bin

**Comment by HelixCreations** [comment]
Hey acs, I was wondering were you able to get it to scale for a 1 to 1 ratio. For instance, seeing the house it was huge, did you get it to scale in MC? 

Also, does your tool support each different type of block? 

I have been trying to find something that will scale my 3d assets correctly in MC for years.

 As I want that one meter in blender or just magic voxel to MC.

Would you know where I could go for something like this? Thanks.

**Comment by acs** [comment]
Hi @HelixCreations ,



> Hey acs, I was wondering were you able to get it to scale for a 1 to 1 ratio. For instance, seeing the house it was huge, did you get it to scale in MC?

No, I have not found a way to fix the scale. And I think that it is not possible to fix this problem in a general way. In order to create models for MC with MV, you need to work in MC scale in MV.
 
> Also, does your tool support each different type of block?

Each different type of block in MC? No, the goal is to support the designs that can be created in MV. And in MV you have:

* Blocks
* Colors
* Materials

Right now the support is pretty  basic. Support the colors using the wood colors in MC. And if you have selected a specific material in MV that exists in MC, use the material to define the block in MC instead of the color (for example, glass material).

> I have been trying to find something that will scale my 3d assets correctly in MC for years.

The problem is that blocks in MC are fixed to 1x1x1 meter and you can not change that. So you need to create your models with this limitation in mind. You can not have a better resolution in MC.

> As I want that one meter in blender or just magic voxel to MC.

In MV just work with this requirement in mind when you create the models: the voxel are 1x1x1 meter.

In blender, I want to play with remesh but at the end, the problem is the same. You can not work in MC with more
detailed models.
 
> Would you know where I could go for something like this? Thanks.

Cheers!
